---
resources:
- name: bbr-image-repo
  type: git
  source:
    uri: https://github.com/EngineerBetter/bbr-image
    branch: master
    paths:
    - assets
    ignore_paths:
    - ci/version

- name: bbr-image-dockerhub
  type: docker-image
  source:
    repository: engineerbetter/bbr-image
    username: ((docker_username))
    password: ((docker_password))

- name: pcf-ops-image
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    username: ((docker_username))
    password: ((docker_password))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:EngineerBetter/bbr-image.git
    branch: master
    file: ci/version
    private_key: ((version_deploy_key))

jobs:
- name: build-image
  serial: true
  plan:
  - aggregate:
    - get: bbr-image-repo
      trigger: true
    - get: pcf-ops-image
    - get: version
      params:
        bump: patch
  - task: prepare-files
    image: pcf-ops-image
    config:
      platform: linux
      inputs:
      - name: bbr-image-repo
      - name: bbr-image-dockerhub
      outputs:
      - name: docker
      run:
        path: sh
        args:
          - -xeuc
          - |
            mv bbr-image-repo/assets/* docker/
  - put: bbr-image-dockerhub
    params:
      build: docker
      tag: version/version
      tag_as_latest: true
  - put: version
    params:
      bump: patch
