---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: bbr-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore
    access_token: ((github_access_token))

- name: om-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: ((github_access_token))

- name: bbr-image-repo
  type: git
  source:
    uri: https://github.com/EngineerBetter/bbr-image
    branch: master
    paths:
    - assets
    - ci/pipeline.yml
    ignore_paths:
    - ci/version

- name: bbr-image-dockerhub
  type: docker-image
  source:
    repository: engineerbetter/bbr-image
    username: ((docker_user))
    password: ((docker_password))

- name: pcf-ops-image
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    username: ((docker_user))
    password: ((docker_password))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:EngineerBetter/bbr-image.git
    branch: master
    file: ci/version
    private_key: ((version_deploy_key.private_key))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack_webhook))

jobs:
- name: build-image
  serial: true
  plan:
  - in_parallel:
    - get: bbr-image-repo
      trigger: true
    - get: bbr-release
      trigger: true
      params:
        globs:
        - bbr-*.tar
    - get: om-github-release
      trigger: true
      params:
        globs: [om-linux-amd64-*.tar.gz]
    - get: pcf-ops-image
    - get: version
      params:
        bump: patch
  - task: prepare-files
    image: pcf-ops-image
    config:
      platform: linux
      inputs:
      - name: bbr-release
      - name: bbr-image-repo
      - name: om-github-release
      outputs:
      - name: docker
      run:
        path: sh
        args:
          - -xeuc
          - |
            mv bbr-image-repo/assets/* docker/
            tar xf bbr-release/bbr-*
            mv releases/bbr docker/bbr
            chmod +x docker/bbr
            tar -C docker -xzf om-github-release/om-linux-amd64-*.tar.gz
  - put: bbr-image-dockerhub
    params:
      build: docker
      tag: version/version
      tag_as_latest: true
  - put: version
    params:
      bump: patch
  - put: slack-alert
    params:
      channel: "#integrations"
      text: |
        Version v${TEXT_FILE_CONTENT} of the bbr-image has been pushed to dockerhub!
      text_file: version/version
